--alter session set "_ORACLE_SCRIPT"=true;
--create user oracle_demo identified by "dudkrish1A";
--COMMIT;

--grant create session to oracle_demo;
--COMMIT;
--ALTER USER oracle_demo quota unlimited on USERS;

create table CREDIT_CARD(card_id number,Card_Type_Code char(2),Card_Type_Full_Name varchar2(100),
                         Issuing_Bank varchar2(100),Card_Number number,Card_Holder_Name varchar2(100),
                         CVV_CVV2 int,Issue_Date date,Expiry_Date date,Billing_Date int,Card_PIN int,Credit_Limit int);

CREATE TABLE "COUNTRIES" (
                             "COUNTRY_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999
                                 INCREMENT BY 1 START WITH 1 CACHE 20,
                             "COUNTRY_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
                             "ALPHA2" CHAR(2 BYTE),
                             "ALPHA3" CHAR(3 BYTE),
                             "COUNTRY_CODE" NUMBER(10,0),
                             "REGION" VARCHAR2(100 BYTE),
                             "SUB_REGION" VARCHAR2(100 BYTE),
                             "INTERMEDIATE_REGION" VARCHAR2(100 BYTE),
                             "REGION_CODE" NUMBER(10,0),
                             "SUB_REGION_CODE" NUMBER(10,0),
                             "INTERMEDIATE_REGION_CODE" NUMBER(10,0),
                             CONSTRAINT "COUNTRY_ID_PK" PRIMARY KEY ("COUNTRY_ID")
);

CREATE TABLE "CROP_INSURANCE"(
                                 "SERIAL_NO" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999
                                     INCREMENT BY 1 START WITH 1 CACHE 20,
                                 "MANDAL_NAME" VARCHAR2(100 BYTE),
                                 "VILLAGE_NAME" VARCHAR2(100 BYTE),
                                 "NAME_OF_THE_BENEFICIARY" VARCHAR2(100 BYTE),
                                 "CROP" VARCHAR2(100 BYTE),
                                 "EXTENT_HA" NUMBER,
                                 "CLAIM_AMOUNT_RS" NUMBER(*,0),
                                 "CATEGORY_LOANEE_NON_LOANEE" VARCHAR2(10 BYTE),
                                 "BANK_NAME" VARCHAR2(100 BYTE),
                                 "BRANCH_NAME" VARCHAR2(100 BYTE),
                                 "ACCOUNT_NUMBER" NUMBER,
                                 CONSTRAINT "SERIAL_NO_PK" PRIMARY KEY ("SERIAL_NO")
) ;

CREATE TABLE "SYSTEM"."INDIA_STATES"
("STATE_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 ,
 "MDDS_STC" NUMBER(*,0),
 "STATE_NAME" VARCHAR2(100 BYTE),
 "MDDS_DTC" NUMBER(*,0),
 "DISTRICT_NAME" VARCHAR2(100 BYTE),
 "MDDS_SUB_DT" NUMBER(*,0),
 "SUB_DISTRICT_NAME" VARCHAR2(100 BYTE),
 "MDDS_PLCN" NUMBER(*,0),
 "AREA_NAME" VARCHAR2(1000 BYTE),
 "STUDENT_ID" NUMBER,
 CONSTRAINT "STATE_ID_PK" PRIMARY KEY ("STATE_ID"),
 CONSTRAINT "STUDENT_INFO_FK" FOREIGN KEY ("STUDENT_ID")
     REFERENCES "SYSTEM"."STUDENT_INFO" ("STUDENT_ID") ENABLE
) ;

create table sales_order(sale_id int,Region varchar2(50),Country varchar2(50),Item_Type varchar2(50),Sales_Channel varchar2(50),
                         Order_Priority char(1),Order_Date date,Order_ID number,Ship_Date date,Units_Sold number,Unit_Price number,
                         Unit_Cost number,Total_Revenue number,Total_Cost number,Total_Profit number);

select * from sales_order;

CREATE TABLE "EMPLOYEES"
(	Emp_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
     "FIRST_NAME" VARCHAR2(50 CHAR),
     LAST_NAME VARCHAR2(50 CHAR),
     "COMPANY_NAME" VARCHAR2(100 CHAR),
     "ADDRESS" VARCHAR2(100 CHAR),
     "CITY" VARCHAR2(100 CHAR),
     "COUNTRY" VARCHAR2(100 CHAR),
     "ZIP" NUMBER,
     "EMP_STATE" VARCHAR2(100 CHAR),
     CONSTRAINT "EMP_ID_PK" PRIMARY KEY ("EMP_ID")
);

CREATE TABLE student_info(
                             student_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                             student_name VARCHAR2(50) NOT NULL,
                             father_name VARCHAR2(50) NOT NULL,
                             gender varchar2(10),
                             MOBILE long,
                             CATEGORY varchar2(20),
                             CONSTRAINT student_id_PK PRIMARY KEY(student_id)
);


create table LASER_SEARCH(LOOKUP_ID number,SERVICE_ID varchar2(50),constraint LOOKUP_ID_PK PRIMARY  KEY(LOOKUP_ID));
CREATE TABLE SERVICE_AUDIT (AUDIT_ID NUMBER,AUDIT_NAME VARCHAR2(50),LOOKUP_ID NUMBER,
                            CONSTRAINT LOOKUP_ID_FK FOREIGN KEY (LOOKUP_ID) REFERENCES LASER_SEARCH (LOOKUP_ID),
                            CONSTRAINT AUDIT_ID_PK PRIMARY KEY (AUDIT_ID)
);
CREATE TABLE CLIENT_AUDIT (CLIENT_AUDIT_ID NUMBER,CLIENT_AUDIT_NAME VARCHAR2(50),SERVICE_AUDIT_ID NUMBER,
                           CONSTRAINT SERVICE_AUDIT_ID_FK FOREIGN KEY (SERVICE_AUDIT_ID) REFERENCES SERVICE_AUDIT (AUDIT_ID),
                           CONSTRAINT CLIENT_AUDIT_ID_PK PRIMARY KEY (CLIENT_AUDIT_ID)
);
select * from LASER_SEARCH;
select * from SERVICE_AUDIT;
select * from CLIENT_AUDIT;

CREATE TABLE EMP (EMPNO NUMBER(4) NOT NULL,ENAME VARCHAR2(10),JOB VARCHAR2(9),
                  MGR NUMBER(4),HIREDATE DATE,SAL NUMBER(7, 2),COMM NUMBER(7, 2),DEPTNO NUMBER(2));
INSERT INTO EMP VALUES (7369, 'SMITH', 'CLERK',    7902, TO_DATE('17-DEC-1980', 'DD-MON-YYYY'), 800, NULL, 20);
INSERT INTO EMP VALUES (7499, 'ALLEN', 'SALESMAN', 7698, TO_DATE('20-FEB-1981', 'DD-MON-YYYY'), 1600, 300, 30);
INSERT INTO EMP VALUES (7521, 'WARD',  'SALESMAN', 7698, TO_DATE('22-FEB-1981', 'DD-MON-YYYY'), 1250, 500, 30);
INSERT INTO EMP VALUES (7566, 'JONES', 'MANAGER',  7839, TO_DATE('2-APR-1981',  'DD-MON-YYYY'), 2975, NULL, 20);
INSERT INTO EMP VALUES (7654, 'MARTIN', 'SALESMAN', 7698,TO_DATE('28-SEP-1981', 'DD-MON-YYYY'), 1250, 1400, 30);
INSERT INTO EMP VALUES (7698, 'BLAKE', 'MANAGER', 7839,TO_DATE('1-MAY-1981', 'DD-MON-YYYY'), 2850, NULL, 30);
INSERT INTO EMP VALUES (7782, 'CLARK', 'MANAGER', 7839,TO_DATE('9-JUN-1981', 'DD-MON-YYYY'), 2450, NULL, 10);
INSERT INTO EMP VALUES (7788, 'SCOTT', 'ANALYST', 7566,TO_DATE('09-DEC-1982', 'DD-MON-YYYY'), 3000, NULL, 20);
INSERT INTO EMP VALUES (7839, 'KING', 'PRESIDENT', NULL,TO_DATE('17-NOV-1981', 'DD-MON-YYYY'), 5000, NULL, 10);
INSERT INTO EMP VALUES (7844, 'TURNER', 'SALESMAN', 7698,TO_DATE('8-SEP-1981', 'DD-MON-YYYY'), 1500, 0, 30);
INSERT INTO EMP VALUES (7876, 'ADAMS', 'CLERK', 7788,TO_DATE('12-JAN-1983', 'DD-MON-YYYY'), 1100, NULL, 20);
INSERT INTO EMP VALUES (7900, 'JAMES', 'CLERK', 7698,TO_DATE('3-DEC-1981', 'DD-MON-YYYY'), 950, NULL, 30);
INSERT INTO EMP VALUES (7902, 'FORD', 'ANALYST', 7566,TO_DATE('3-DEC-1981', 'DD-MON-YYYY'), 3000, NULL, 20);
INSERT INTO EMP VALUES (7934, 'MILLER', 'CLERK', 7782,TO_DATE('23-JAN-1982', 'DD-MON-YYYY'), 1300, NULL, 10);

CREATE TABLE "EMPLOYEE_AUDITING" (
                                     "EMP_AUDIT_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999
                                         INCREMENT BY 1 START WITH 1 CACHE 20,
                                     "FIRST_NAME" VARCHAR2(50 CHAR),
                                     LAST_NAME VARCHAR2(50 CHAR),
                                     "COMPANY_NAME" VARCHAR2(100 CHAR),
                                     created_by varchar2(45 CHAR) ,
                                     created_date TIMESTAMP,
                                     modified_by varchar2(45 CHAR) ,
                                     modified_date TIMESTAMP,
                                     CONSTRAINT "EMP_AUDIT_ID_PK" PRIMARY KEY ("EMP_AUDIT_ID")
);